# Generated by Django 3.2.5 on 2022-06-03 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('paciente_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('paciente_ci', models.CharField(max_length=10)),
                ('paciente_nombre_completo', models.CharField(max_length=100)),
                ('paciente_fechanac', models.DateField()),
                ('paciente_celular', models.CharField(max_length=10)),
                ('paciente_email', models.EmailField(max_length=254)),
                ('paciente_genero', models.CharField(max_length=30)),
                ('profesion', models.CharField(max_length=30)),
                ('estado_civil', models.CharField(max_length=30)),
                ('grado_instruccion', models.CharField(max_length=30)),
                ('estado_salud', models.CharField(max_length=30)),
                ('observaciones', models.CharField(max_length=1000)),
                ('direccion', models.CharField(max_length=100)),
                ('puntaje_minimental', models.PositiveIntegerField()),
                ('medicacion', models.CharField(max_length=100)),
                ('lugarnac', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('personal_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('personal_ci', models.CharField(max_length=10)),
                ('personal_nombre_completo', models.CharField(max_length=100)),
                ('personal_fechanac', models.DateField()),
                ('personal_celular', models.CharField(max_length=10)),
                ('personal_email', models.EmailField(max_length=254)),
                ('personal_genero', models.CharField(max_length=30)),
                ('especialidad', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='referencia_contacto',
            fields=[
                ('referencia_contacto_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=10)),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurolab.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='idioma',
            fields=[
                ('idioma_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=30)),
                ('nativo', models.BooleanField()),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurolab.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='hijo',
            fields=[
                ('hijo_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('hijo_ci', models.PositiveIntegerField()),
                ('hijo_nombre_completo', models.CharField(max_length=100)),
                ('hijo_fechanac', models.DateField()),
                ('hijo_celular', models.CharField(max_length=10)),
                ('hijo_email', models.EmailField(max_length=254)),
                ('hijo_genero', models.CharField(max_length=30)),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurolab.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='encuesta',
            fields=[
                ('gds_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_prueba', models.CharField(max_length=100)),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=30)),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurolab.paciente')),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurolab.personal')),
            ],
        ),
        migrations.CreateModel(
            name='condicion_medica',
            fields=[
                ('condicion_medica_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('enfermedad', models.CharField(max_length=300)),
                ('medicacion', models.CharField(max_length=30)),
                ('nativo', models.BooleanField()),
                ('fecha_inicio', models.DateField()),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurolab.paciente')),
            ],
        ),
    ]
