# Generated by Django 3.2.5 on 2022-06-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurolab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='pac',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='per',
        ),
        migrations.RemoveField(
            model_name='hijo',
            name='pac',
        ),
        migrations.RemoveField(
            model_name='idioma',
            name='pac',
        ),
        migrations.RemoveField(
            model_name='referencia_contacto',
            name='pac',
        ),
        migrations.DeleteModel(
            name='condicion_medica',
        ),
        migrations.DeleteModel(
            name='encuesta',
        ),
        migrations.DeleteModel(
            name='hijo',
        ),
        migrations.DeleteModel(
            name='idioma',
        ),
        migrations.DeleteModel(
            name='paciente',
        ),
        migrations.DeleteModel(
            name='personal',
        ),
        migrations.DeleteModel(
            name='referencia_contacto',
        ),
    ]
